#!/usr/bin/env python3
"""Assemble Plan-A server package and local credential tools package."""

from __future__ import annotations

import argparse
import json
import shutil
import stat
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent
RELEASE = ROOT / "release"

SERVER_FILES = [
    "main.py",
    "webapp.py",
    "monitor.py",
    "history.py",
    "settings_store.py",
    "auth_control.py",
    "getInfo.py",
    "env.py",
    "emailSend.py",
    "encrypt.js",
    "data.json",
    "index.py",  # legacy entry → webapp
]

LOCAL_FILES = [
    "getInfo.py",
    "env.py",
    "encrypt.js",
    "browser_session.py",
    "bootstrap_browser.py",
    "bootstrap_browser.ps1",
    "refresh_credentials.py",
    "refresh_credentials.ps1",
    "bootstrap_session.py",
    "bootstrap.ps1",
]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _chmod_x(path: Path) -> None:
    try:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


# Fully automatic Plan-A deploy: install deps, fix env, place session,
# probe API, install+enable+start systemd (nohup fallback).
# Keep as raw string (not f-string) so bash braces need no escaping.
DEPLOY_SH = r'''#!/usr/bin/env bash
# Fully automatic Plan A Linux deploy (session-cookie only; no GUI / MFA).
# Generated by package_release.py — LF newlines + executable bit.

set -euo pipefail

# ── 0. Constants / env defaults ──────────────────────────────────────────────
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

export NONINTERACTIVE="${NONINTERACTIVE:-1}"
export DEBIAN_FRONTEND=noninteractive

PYTHON_BIN="${PYTHON_BIN:-python3}"
VENV_DIR="${VENV_DIR:-.venv}"
ROOMINFO_USER="${ROOMINFO_USER:-}"
ROOMINFO_GROUP="${ROOMINFO_GROUP:-${ROOMINFO_USER}}"
SESSION_SRC="${SESSION_SRC:-}"
SKIP_PROBE="${SKIP_PROBE:-0}"
FORCE_START="${FORCE_START:-0}"
FORCE_RESTART="${FORCE_RESTART:-0}"
START_MODE="${START_MODE:-auto}"   # auto|systemd|nohup|none
SERVICE_NAME="${SERVICE_NAME:-roominfo}"
UNIT_DST="/etc/systemd/system/${SERVICE_NAME}.service"
PID_DIR="${PID_DIR:-./run}"
PID_FILE="${PID_FILE:-$PID_DIR/roominfo.pid}"
LOG_FILE="${LOG_FILE:-$PID_DIR/roominfo.log}"
SESSION_DST="./data/.uestc_session.json"
# Exit codes: 0 ok; 1 hard fail; 2 probe/session soft-fail (install done, not started unless FORCE_START)

PROBE_FAILED=0
SESSION_PATH=""
VENV_PY=""
RESOLVED_START=""
RESOLVED_USER=""
RESOLVED_GROUP=""

log()  { echo "[deploy] $*"; }
warn() { echo "[deploy] WARNING: $*" >&2; }
die()  { echo "[deploy] ERROR: $*" >&2; exit 1; }

# ── 1. Privilege helpers ─────────────────────────────────────────────────────
have_cmd() { command -v "$1" >/dev/null 2>&1; }
is_root()  { [ "$(id -u)" -eq 0 ]; }
can_sudo() { have_cmd sudo && sudo -n true 2>/dev/null; }
run_priv() {
  if is_root; then
    "$@"
  elif can_sudo; then
    sudo -n "$@"
  else
    return 1
  fi
}
can_priv() {
  if is_root; then
    return 0
  fi
  if can_sudo; then
    return 0
  fi
  return 1
}

# ── 2. OS packages (python3, venv, nodejs) ───────────────────────────────────
ensure_system_deps() {
  local need_python=0 need_venv=0 need_node=0
  local pkgs=()

  if ! have_cmd python3 && ! have_cmd "$PYTHON_BIN"; then
    need_python=1
  fi

  if have_cmd "$PYTHON_BIN" || have_cmd python3; then
    local py="$PYTHON_BIN"
    have_cmd "$py" || py=python3
    if ! "$py" -c 'import venv' 2>/dev/null; then
      need_venv=1
    fi
  else
    need_venv=1
  fi

  if ! have_cmd node && ! have_cmd nodejs; then
    need_node=1
  fi

  if [ "$need_python" -eq 0 ] && [ "$need_venv" -eq 0 ] && [ "$need_node" -eq 0 ]; then
    log "system deps ok (python/venv present; node present)"
    return 0
  fi

  if can_priv; then
    log "installing missing system packages..."
    if have_cmd apt-get; then
      pkgs=()
      [ "$need_python" -eq 1 ] || [ "$need_venv" -eq 1 ] && pkgs+=(python3 python3-venv python3-pip)
      [ "$need_node" -eq 1 ] && pkgs+=(nodejs)
      if [ "${#pkgs[@]}" -gt 0 ]; then
        run_priv apt-get update -y
        run_priv apt-get install -y "${pkgs[@]}"
      fi
    elif have_cmd dnf; then
      pkgs=()
      [ "$need_python" -eq 1 ] || [ "$need_venv" -eq 1 ] && pkgs+=(python3 python3-pip)
      [ "$need_node" -eq 1 ] && pkgs+=(nodejs)
      [ "${#pkgs[@]}" -gt 0 ] && run_priv dnf install -y "${pkgs[@]}"
    elif have_cmd yum; then
      pkgs=()
      [ "$need_python" -eq 1 ] || [ "$need_venv" -eq 1 ] && pkgs+=(python3 python3-pip)
      [ "$need_node" -eq 1 ] && pkgs+=(nodejs)
      [ "${#pkgs[@]}" -gt 0 ] && run_priv yum install -y "${pkgs[@]}"
    elif have_cmd apk; then
      pkgs=()
      [ "$need_python" -eq 1 ] || [ "$need_venv" -eq 1 ] && pkgs+=(python3 py3-pip py3-virtualenv)
      [ "$need_node" -eq 1 ] && pkgs+=(nodejs)
      [ "${#pkgs[@]}" -gt 0 ] && run_priv apk add --no-cache "${pkgs[@]}"
    else
      warn "no known package manager; install python3 / python3-venv / nodejs manually if needed"
    fi
  else
    warn "missing system deps and no root/passwordless sudo; continuing with what is available"
  fi

  if ! have_cmd python3 && ! have_cmd "$PYTHON_BIN"; then
    if have_cmd apt-get; then
      die "python3 missing and cannot install. Run: sudo apt-get install -y python3 python3-venv python3-pip"
    elif have_cmd dnf; then
      die "python3 missing and cannot install. Run: sudo dnf install -y python3 python3-pip"
    elif have_cmd yum; then
      die "python3 missing and cannot install. Run: sudo yum install -y python3 python3-pip"
    else
      die "python3 missing and cannot install via apt/dnf/yum"
    fi
  fi

  if ! have_cmd node && ! have_cmd nodejs; then
    warn "node/nodejs not found. Only needed for password-login fallback via encrypt.js; Plan A prefers session cookies."
  fi
}

# ── 3. Venv + pip ────────────────────────────────────────────────────────────
ensure_venv() {
  local py="$PYTHON_BIN"
  have_cmd "$py" || py=python3

  if [ -x "$VENV_DIR/bin/python" ]; then
    log "reusing venv: $VENV_DIR"
  else
    if [ -d "$VENV_DIR" ]; then
      warn "venv broken (no $VENV_DIR/bin/python); recreating"
      rm -rf "$VENV_DIR"
    fi
    log "creating venv: $VENV_DIR"
    if ! "$py" -m venv "$VENV_DIR"; then
      if have_cmd apt-get; then
        die "failed to create venv. Install: sudo apt-get install -y python3-venv  then re-run."
      fi
      die "failed to create venv (python3 -m venv). Install python3-venv / ensurepip then re-run."
    fi
  fi

  VENV_PY="$VENV_DIR/bin/python"
  if [ ! -x "$VENV_PY" ]; then
    die "venv python missing: $VENV_PY"
  fi

  if [ ! -f requirements.txt ]; then
    die "requirements.txt missing — package corrupt"
  fi

  log "installing Python dependencies"
  "$VENV_PY" -m pip install --upgrade pip >/dev/null
  "$VENV_PY" -m pip install -r requirements.txt
}

# ── 4. data/ directory ───────────────────────────────────────────────────────
ensure_dirs() {
  mkdir -p data "$PID_DIR"
  chmod 700 data 2>/dev/null || true
  chmod 700 "$PID_DIR" 2>/dev/null || true
  : > data/.gitkeep
}

# ── 5. .env bootstrap + Plan A key enforcement ───────────────────────────────
# Upsert KEY=VALUE lines; preserve comments and unknown keys.
env_upsert() {
  # env_upsert KEY VALUE  (VALUE written as-is after =)
  local key="$1"
  local val="$2"
  "$VENV_PY" - "$key" "$val" <<'PY'
import re
import sys
from pathlib import Path

key, val = sys.argv[1], sys.argv[2]
path = Path(".env")
text = path.read_text(encoding="utf-8") if path.exists() else ""
lines = text.splitlines()
out = []
seen = False
pat = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=")
for line in lines:
    m = pat.match(line)
    if m and m.group(1) == key:
        out.append(f"{key}={val}")
        seen = True
    else:
        out.append(line)
if not seen:
    if out and out[-1].strip() != "":
        out.append("")
    out.append(f"{key}={val}")
path.write_text("\n".join(out) + "\n", encoding="utf-8")
PY
}

ensure_env() {
  if [ ! -f .env ]; then
    if [ -f .env.example ]; then
      cp .env.example .env
      log "created .env from .env.example"
    else
      die "missing .env and .env.example"
    fi
  fi
  chmod 600 .env 2>/dev/null || true

  # Always force Plan A keys (idempotent; never invent secrets).
  env_upsert "ONLINE_SESSION_FILE" '"./data/.uestc_session.json"'
  env_upsert "ONLINE_BROWSER_REFRESH" '"false"'

  # Optional passthrough of real secrets from the calling environment only.
  if [ -n "${API_USERNAME:-}" ]; then
    env_upsert "API_USERNAME" "\"${API_USERNAME}\""
  fi
  if [ -n "${API_PASSWORD:-}" ]; then
    env_upsert "API_PASSWORD" "\"${API_PASSWORD}\""
  fi
  if [ -n "${Authorization_code:-}" ]; then
    env_upsert "Authorization_code" "\"${Authorization_code}\""
  fi

  log "Plan A env keys enforced (ONLINE_SESSION_FILE, ONLINE_BROWSER_REFRESH=false)"
}

# ── 6. Session auto-discovery ────────────────────────────────────────────────
discover_session() {
  SESSION_PATH=""
  local candidates=()
  local c found=""

  # Order: already at DST, SESSION_SRC, project root, /tmp variants
  candidates+=("$SESSION_DST")
  [ -n "$SESSION_SRC" ] && candidates+=("$SESSION_SRC")
  candidates+=(
    "./.uestc_session.json"
    "./deploy_bundle/.uestc_session.json"
    "/tmp/uestc_session.json"
    "/tmp/.uestc_session.json"
  )

  for c in "${candidates[@]}"; do
    if [ -n "$c" ] && [ -f "$c" ]; then
      found="$c"
      break
    fi
  done

  if [ -z "$found" ]; then
    warn "no session file discovered"
    SESSION_PATH=""
    return 0
  fi

  if [ "$found" != "$SESSION_DST" ]; then
    cp "$found" "$SESSION_DST"
    log "session installed from: $found -> $SESSION_DST"
  else
    log "session found: $SESSION_DST"
  fi
  chmod 600 "$SESSION_DST" 2>/dev/null || true
  SESSION_PATH="$SESSION_DST"
}

# ── 7. Credential gate (zero interactive) ────────────────────────────────────
gate_credentials() {
  local has_session=0
  local flags

  [ -n "${SESSION_PATH:-}" ] && [ -f "$SESSION_PATH" ] && has_session=1

  # Presence flags only — never export secret values into the shell.
  flags="$("$VENV_PY" - <<'PY'
from pathlib import Path
import re

text = Path(".env").read_text(encoding="utf-8") if Path(".env").exists() else ""
vals = {}
for line in text.splitlines():
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", line)
    if not m:
        continue
    k, v = m.group(1), m.group(2).strip()
    if len(v) >= 2 and ((v[0] == v[-1] == '"') or (v[0] == v[-1] == "'")):
        v = v[1:-1]
    vals[k] = v

placeholders = {"", "Your Username", "your_username", "Your Password", "Your SmtpPassword"}
user = vals.get("API_USERNAME", "")
password = vals.get("API_PASSWORD", "")
smtp = vals.get("Authorization_code", "")
cookie = vals.get("ONLINE_COOKIE", "") or vals.get("IDAS_COOKIE", "")
token = vals.get("ONLINE_TOKEN", "")
has_user = "1" if user not in placeholders else "0"
has_pass = "1" if password not in placeholders else "0"
smtp_ph = "1" if (not smtp or smtp in placeholders) else "0"
has_ct = "1" if (cookie or token) else "0"
print(f"{has_user} {has_pass} {smtp_ph} {has_ct}")
PY
)"
  # shellcheck disable=SC2086
  set -- $flags
  local has_user="${1:-0}"
  local has_pass="${2:-0}"
  local smtp_placeholder="${3:-1}"
  local has_cookie_or_token="${4:-0}"
  local has_password_pair=0
  if [ "$has_user" = "1" ] && [ "$has_pass" = "1" ]; then
    has_password_pair=1
  fi

  # Plan A prefers session; password fallback requires BOTH username and password.
  if [ "$has_session" -eq 0 ] && [ "$has_password_pair" -eq 0 ] && [ "$has_cookie_or_token" -eq 0 ]; then
    die "no usable auth material.
Provide ONE of:
  1) scp session to $SESSION_DST
  2) SESSION_SRC=/path/to/.uestc_session.json $0
  3) real API_USERNAME and API_PASSWORD together in .env (password fallback needs nodejs)
  4) ONLINE_COOKIE or ONLINE_TOKEN in .env"
  fi

  if [ "$has_session" -eq 0 ] && [ "$has_user" = "1" ] && [ "$has_pass" = "0" ] && [ "$has_cookie_or_token" -eq 0 ]; then
    die "API_USERNAME set but API_PASSWORD missing/placeholder (and no session/cookie/token).
Fill both API_USERNAME and API_PASSWORD, or provide data/.uestc_session.json"
  fi

  if [ "$smtp_placeholder" = "1" ]; then
    warn "Authorization_code missing/placeholder — monitor will run but email notify may fail"
  fi
}

# ── 8. Import check ──────────────────────────────────────────────────────────
verify_imports() {
  log "verifying imports / Plan A config"
  "$VENV_PY" - <<'PY'
import env
import getInfo
import webapp
import monitor
import history

assert env.online_browser_refresh is False, "ONLINE_BROWSER_REFRESH must be false on server"
session = str(getattr(env, "online_session_file", "") or "")
assert "data" in session.replace("\\", "/"), f"session path should point under data/: {session!r}"
print("imports_ok")
print("browser_refresh=", env.online_browser_refresh)
print("session_file=", session)
user = getattr(env, "username", "") or ""
print("username_configured=", bool(user) and user not in {"Your Username", "your_username", ""})
smtp = getattr(env, "Authorization_code", "") or ""
print("smtp_configured=", bool(smtp) and smtp not in {"Your SmtpPassword", ""})
PY
}

# ── 9. Probe ─────────────────────────────────────────────────────────────────
probe_session() {
  PROBE_FAILED=0
  if [ "$SKIP_PROBE" = "1" ]; then
    log "SKIP_PROBE=1 — skipping getInfo probe"
    return 0
  fi
  if [ -z "${SESSION_PATH:-}" ] || [ ! -f "${SESSION_PATH}" ]; then
    log "no session file — skipping probe (password/cookie fallback may still work at runtime)"
    return 0
  fi

  log "probing /site/bedroom once via getInfo.py"
  local rc=0
  set +e
  "$VENV_PY" getInfo.py
  rc=$?
  set -e
  if [ "$rc" -ne 0 ]; then
    warn "probe failed (rc=$rc). Session may be expired — refresh on local machine, then scp."
    warn "local: refresh_credentials.ps1  →  scp deploy_bundle/.uestc_session.json host:$ROOT_DIR/data/"
    PROBE_FAILED=1
  else
    log "probe succeeded"
  fi
}

# ── 10. Generate runtime unit from template ──────────────────────────────────
resolve_service_identity() {
  if [ -n "$ROOMINFO_USER" ]; then
    RESOLVED_USER="$ROOMINFO_USER"
  elif is_root; then
    RESOLVED_USER="roominfo"
  else
    RESOLVED_USER="$(id -un)"
  fi

  if [ -n "$ROOMINFO_GROUP" ]; then
    RESOLVED_GROUP="$ROOMINFO_GROUP"
  else
    RESOLVED_GROUP="$(id -gn "$RESOLVED_USER" 2>/dev/null || echo "$RESOLVED_USER")"
  fi

  # If root and target user missing, create a system account.
  if is_root && [ "$RESOLVED_USER" = "roominfo" ] && ! id "$RESOLVED_USER" >/dev/null 2>&1; then
    log "creating system user: roominfo"
    if have_cmd useradd; then
      useradd -r -s /usr/sbin/nologin -d "$ROOT_DIR" roominfo 2>/dev/null \
        || useradd -r -s /sbin/nologin -d "$ROOT_DIR" roominfo 2>/dev/null \
        || warn "useradd roominfo failed; continuing with available identity"
    fi
  fi

  if [ -z "$ROOMINFO_GROUP" ]; then
    RESOLVED_GROUP="$(id -gn "$RESOLVED_USER" 2>/dev/null || echo "$RESOLVED_USER")"
  fi
}

render_unit() {
  resolve_service_identity
  local tpl="./roominfo.service"
  local out="./roominfo.service.generated"
  local py_abs main_abs

  py_abs="$ROOT_DIR/$VENV_DIR/bin/python"
  main_abs="$ROOT_DIR/main.py"

  if [ ! -f "$tpl" ]; then
    # Fallback template if package unit missing.
    cat > "$tpl" <<EOF
[Unit]
Description=UESTC dorm electricity monitor (Plan A)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=/opt/roominfo
User=roominfo
Group=roominfo
Environment=PYTHONUNBUFFERED=1
Environment=ONLINE_BROWSER_REFRESH=false
ExecStart=/opt/roominfo/.venv/bin/python /opt/roominfo/main.py
Restart=always
RestartSec=10
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  fi

  # Rewrite WorkingDirectory / ExecStart / User / Group from template.
  "$VENV_PY" - "$tpl" "$out" "$ROOT_DIR" "$py_abs" "$main_abs" "$RESOLVED_USER" "$RESOLVED_GROUP" <<'PY'
import sys
from pathlib import Path

tpl, out, root, py_abs, main_abs, user, group = sys.argv[1:8]
text = Path(tpl).read_text(encoding="utf-8")
lines = []
for line in text.splitlines():
    if line.startswith("WorkingDirectory="):
        lines.append(f"WorkingDirectory={root}")
    elif line.startswith("ExecStart="):
        lines.append(f"ExecStart={py_abs} {main_abs}")
    elif line.startswith("User="):
        lines.append(f"User={user}")
    elif line.startswith("Group="):
        lines.append(f"Group={group}")
    else:
        lines.append(line)
# Ensure Environment ONLINE_SESSION_FILE absolute path present
joined = "\n".join(lines)
if "ONLINE_SESSION_FILE=" not in joined:
    # insert after first Environment= line if any, else after [Service]
    out_lines = []
    inserted = False
    for line in lines:
        out_lines.append(line)
        if not inserted and line.startswith("Environment="):
            out_lines.append(f"Environment=ONLINE_SESSION_FILE={root}/data/.uestc_session.json")
            inserted = True
        elif not inserted and line.strip() == "[Service]":
            # wait for next chance
            pass
    if not inserted:
        # append before [Install] or end
        final = []
        done = False
        for line in out_lines:
            if not done and line.strip() == "[Install]":
                final.append(f"Environment=ONLINE_SESSION_FILE={root}/data/.uestc_session.json")
                done = True
            final.append(line)
        if not done:
            final.append(f"Environment=ONLINE_SESSION_FILE={root}/data/.uestc_session.json")
        out_lines = final
    lines = out_lines
Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")
print(out)
PY
  log "wrote generated unit: $out (User=$RESOLVED_USER Group=$RESOLVED_GROUP)"
}

# ── 11. Start modes ──────────────────────────────────────────────────────────
resolve_start_mode() {
  case "$START_MODE" in
    none|systemd|nohup)
      RESOLVED_START="$START_MODE"
      ;;
    auto|*)
      if have_cmd systemctl && can_priv; then
        RESOLVED_START="systemd"
      else
        RESOLVED_START="nohup"
      fi
      ;;
  esac
  log "resolved start mode: $RESOLVED_START (requested=$START_MODE)"
}

start_systemd() {
  if ! have_cmd systemctl; then
    die "START_MODE=systemd but systemctl not found"
  fi
  if ! can_priv; then
    die "START_MODE=systemd requires root or passwordless sudo.
Re-run: sudo $0
Or: START_MODE=nohup $0"
  fi

  render_unit

  # Ownership when running as root for a dedicated service user.
  if is_root && [ "$RESOLVED_USER" != "root" ] && id "$RESOLVED_USER" >/dev/null 2>&1; then
    chown -R "$RESOLVED_USER:$RESOLVED_GROUP" \
      "$ROOT_DIR/data" "$ROOT_DIR/$PID_DIR" 2>/dev/null || true
    chown "$RESOLVED_USER:$RESOLVED_GROUP" "$ROOT_DIR/.env" 2>/dev/null || true
    [ -f "$SESSION_DST" ] && chown "$RESOLVED_USER:$RESOLVED_GROUP" "$SESSION_DST" 2>/dev/null || true
    # venv must be readable/executable by service user
    chown -R "$RESOLVED_USER:$RESOLVED_GROUP" "$ROOT_DIR/$VENV_DIR" 2>/dev/null || true
  fi

  log "installing systemd unit: $UNIT_DST"
  run_priv cp "$ROOT_DIR/roominfo.service.generated" "$UNIT_DST"
  run_priv systemctl daemon-reload
  run_priv systemctl enable --now "$SERVICE_NAME"
  sleep 1

  if run_priv systemctl is-active --quiet "$SERVICE_NAME"; then
    log "systemd: $SERVICE_NAME is active"
    run_priv systemctl --no-pager --full status "$SERVICE_NAME" 2>/dev/null | head -n 20 || true
    log "logs: journalctl -u $SERVICE_NAME -f"
    return 0
  fi

  warn "systemd unit installed but not active"
  run_priv systemctl --no-pager --full status "$SERVICE_NAME" 2>/dev/null | head -n 40 || true
  run_priv journalctl -u "$SERVICE_NAME" -n 20 --no-pager 2>/dev/null || true
  die "systemd enable/start failed for $SERVICE_NAME"
}

start_nohup() {
  local py_abs main_abs oldpid=""
  mkdir -p "$PID_DIR"
  chmod 700 "$PID_DIR" 2>/dev/null || true
  py_abs="$ROOT_DIR/$VENV_DIR/bin/python"
  main_abs="$ROOT_DIR/main.py"

  if [ -f "$PID_FILE" ]; then
    oldpid="$(cat "$PID_FILE" 2>/dev/null || true)"
    if [ -n "${oldpid:-}" ] && kill -0 "$oldpid" 2>/dev/null; then
      if [ "$FORCE_RESTART" = "1" ]; then
        log "FORCE_RESTART=1 — stopping pid $oldpid"
        kill "$oldpid" 2>/dev/null || true
        sleep 1
        kill -9 "$oldpid" 2>/dev/null || true
      else
        log "already running (pid=$oldpid) — idempotent skip (FORCE_RESTART=1 to restart)"
        return 0
      fi
    fi
  fi

  log "starting with nohup -> $LOG_FILE"
  nohup "$py_abs" "$main_abs" >>"$LOG_FILE" 2>&1 &
  echo $! >"$PID_FILE"
  sleep 1
  if kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    log "nohup started pid=$(cat "$PID_FILE")"
    log "stop: kill \$(cat $PID_FILE)"
    return 0
  fi
  die "nohup process dead immediately after start; see $LOG_FILE"
}

start_none() {
  log "START_MODE=none — install/configure only, not starting monitor"
  log "manual start options:"
  log "  systemd: START_MODE=systemd sudo -E $0"
  log "  nohup:   START_MODE=nohup $0"
  log "  direct:  $VENV_DIR/bin/python main.py"
}

start_monitor() {
  resolve_start_mode
  case "$RESOLVED_START" in
    none)
      start_none
      ;;
    systemd)
      start_systemd
      ;;
    nohup)
      start_nohup
      ;;
    *)
      die "unknown start mode: $RESOLVED_START"
      ;;
  esac
}

print_summary() {
  echo
  log "======== summary ========"
  log "project:     $ROOT_DIR"
  log "venv:        $VENV_DIR  ($VENV_PY)"
  log "session:     ${SESSION_PATH:-"(none)"}"
  log "start_mode:  requested=$START_MODE resolved=${RESOLVED_START:-"(not started)"}"
  log "probe:       $([ "${PROBE_FAILED:-0}" = "1" ] && echo FAILED || echo ok/skipped)"
  log "service:     $SERVICE_NAME"
  if [ "${RESOLVED_START:-}" = "systemd" ]; then
    log "unit:        $UNIT_DST"
    log "user:        ${RESOLVED_USER:-?} / ${RESOLVED_GROUP:-?}"
    log "logs:        journalctl -u $SERVICE_NAME -f"
  elif [ "${RESOLVED_START:-}" = "nohup" ]; then
    log "pidfile:     $PID_FILE"
    log "logfile:     $LOG_FILE"
  fi
  log "one-shot:    $VENV_DIR/bin/python getInfo.py"
  log "re-deploy:   ./deploy.sh"
  log "MFA refresh (local desktop, then scp session):"
  log "  refresh_credentials.ps1 --export-dir .\\deploy_bundle"
  log "  scp deploy_bundle/.uestc_session.json user@host:$ROOT_DIR/data/.uestc_session.json"
  log "  ssh user@host 'cd $ROOT_DIR && ./deploy.sh'"
  log "========================="
}

# ── 12. Main orchestration ───────────────────────────────────────────────────
main() {
  log "project=$ROOT_DIR mode=$START_MODE noninteractive=$NONINTERACTIVE"
  ensure_system_deps
  ensure_dirs
  ensure_venv
  ensure_env
  discover_session
  gate_credentials
  verify_imports
  probe_session

  if [ "${PROBE_FAILED:-0}" = "1" ] && [ "$FORCE_START" != "1" ]; then
    warn "probe failed — install complete; refusing auto-start (FORCE_START=1 to override)"
    print_summary
    exit 2
  fi

  if [ "$START_MODE" != "none" ]; then
    start_monitor
  else
    RESOLVED_START="none"
    start_none
  fi

  print_summary
  if [ "${PROBE_FAILED:-0}" = "1" ]; then
    exit 2
  fi
  exit 0
}

main "$@"
'''


def build_server_package(out_dir: Path, with_session: bool) -> dict:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for name in SERVER_FILES:
        src = ROOT / name
        if src.exists():
            _copy(src, out_dir / name)

    for folder in ("templates", "static"):
        src_dir = ROOT / folder
        if src_dir.is_dir():
            shutil.copytree(src_dir, out_dir / folder, dirs_exist_ok=True)

    data_src = ROOT / "data.json"
    if data_src.exists():
        _copy(data_src, out_dir / "data.json")
    else:
        _write(out_dir / "data.json", "[]\n")

    _write(
        out_dir / "requirements.txt",
        "\n".join(
            [
                "flask==3.0.0",
                "requests==2.31.0",
                "beautifulsoup4==4.12.2",
                "python-dotenv==1.0.0",
                "schedule==1.2.1",
                "pyexecjs==1.5.1",
                "",
            ]
        ),
    )

    _write(
        out_dir / ".env.example",
        "\n".join(
            [
                "# ===== 方案 A：无 GUI 服务器 =====",
                "# 一条命令自动部署（venv / Plan A 配置 / session / 探测 / systemd|nohup）：",
                "#   SESSION_SRC=/path/to/.uestc_session.json ./deploy.sh",
                "# 或 session 已在 data/.uestc_session.json / /tmp 时直接：",
                "#   ./deploy.sh",
                "",
                'API_USERNAME="Your Username"',
                'API_PASSWORD="Your Password"',
                'Authorization_code="Your SmtpPassword"',
                'SMTP_SERVER="smtp.163.com"',
                'SMTP_PORT="465"',
                'SMTP_FROM="your_account@163.com"',
                'SMTP_FROM_NAME="roominfo"',
                'SMTP_USE_SSL="true"',
                'DATA_FILE="./data.json"',
                'CHECK_INTERVAL_MINUTES="60"',
                'LOW_BALANCE_THRESHOLD="20"',
                "",
                'HISTORY_DB="./data/history.db"',
                'HISTORY_RETAIN_DAYS="90"',
                'WEB_HOST="0.0.0.0"',
                'WEB_PORT="8080"',
                'WEB_AUTH_TOKEN="change-me-to-a-long-random-token"',
                'AUTH_MODE="manual"',
                "",
                "# 服务器只使用 Cookie 会话，不要开浏览器刷新（deploy.sh 会强制这两项）",
                'ONLINE_SESSION_FILE="./data/.uestc_session.json"',
                'ONLINE_BROWSER_REFRESH="false"',
                'ONLINE_REMEMBER_ME="true"',
                "",
                'ONLINE_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"',
                'ONLINE_ACCEPT_LANGUAGE="zh-CN,zh;q=0.9,en;q=0.8"',
                "",
                'ONLINE_TOKEN=""',
                'ONLINE_COOKIE=""',
                'IDAS_COOKIE=""',
                "",
            ]
        ),
    )

    _write(out_dir / "deploy.sh", DEPLOY_SH)
    _chmod_x(out_dir / "deploy.sh")

    # Documented default for /opt/roominfo; deploy.sh rewrites paths/user at runtime.
    _write(
        out_dir / "roominfo.service",
        "\n".join(
            [
                "[Unit]",
                "Description=UESTC dorm electricity monitor (Plan A)",
                "After=network-online.target",
                "Wants=network-online.target",
                "",
                "[Service]",
                "Type=simple",
                "WorkingDirectory=/opt/roominfo",
                "User=roominfo",
                "Group=roominfo",
                "Environment=PYTHONUNBUFFERED=1",
                "Environment=ONLINE_BROWSER_REFRESH=false",
                "ExecStart=/opt/roominfo/.venv/bin/python /opt/roominfo/main.py",
                "Restart=always",
                "RestartSec=10",
                "NoNewPrivileges=true",
                "PrivateTmp=true",
                "",
                "[Install]",
                "WantedBy=multi-user.target",
                "",
            ]
        ),
    )

    readme = f"""# 服务端包（方案 A）

生成时间: {datetime.now(timezone.utc).isoformat()}

## 这是什么

无 GUI 服务器部署包：只依赖 Cookie 会话，不安装 Playwright/浏览器。

## 一键部署

```bash
# After scp of server-plan-a/ (and optional session):
cd /opt/roominfo && chmod +x deploy.sh && \\
  SESSION_SRC=/path/to/.uestc_session.json ./deploy.sh
# Or if session already at data/.uestc_session.json or /tmp/uestc_session.json:
cd /opt/roominfo && ./deploy.sh
```

`./deploy.sh` 全自动完成：

- 有 root/免密 sudo 时安装 OS 依赖（`python3-venv`、`nodejs`）
- 创建 `.venv`，`pip install -r requirements.txt`
- 种子/锁定 Plan A 配置：`ONLINE_SESSION_FILE=./data/.uestc_session.json`，`ONLINE_BROWSER_REFRESH=false`
- 发现并复制 session（`SESSION_SRC` / `data/` / 包根 / `/tmp/...`）
- 探测 `getInfo.py`（`/site/bedroom`）
- 有权限则装 systemd 并 `enable --now`；否则 `nohup`（`./run/roominfo.pid` + `./run/roominfo.log`）

### 常用覆盖变量

| 变量 | 默认 | 含义 |
|------|------|------|
| `SESSION_SRC` | 空 | 复制此 session 到 `data/` |
| `START_MODE` | `auto` | `auto` \\| `systemd` \\| `nohup` \\| `none` |
| `FORCE_START` | `0` | 探测失败仍启动 |
| `SKIP_PROBE` | `0` | 跳过 getInfo 探测 |
| `FORCE_RESTART` | `0` | nohup 已在跑时强制重启 |
| `ROOMINFO_USER` | 空 | systemd `User=`（root 默认 `roominfo`，否则当前用户） |
| `NONINTERACTIVE` | `1` | 禁止交互（始终） |
| `VENV_DIR` | `.venv` | venv 路径 |
| `PYTHON_BIN` | `python3` | 创建 venv 用的系统 Python |
| `SERVICE_NAME` | `roominfo` | systemd 单元名 |

```bash
START_MODE=systemd ./deploy.sh          # force systemd
START_MODE=nohup ./deploy.sh            # force nohup+pidfile
START_MODE=none ./deploy.sh             # install only, do not start
FORCE_START=1 ./deploy.sh               # start even if probe fails
SKIP_PROBE=1 ./deploy.sh                # skip getInfo probe
ROOMINFO_USER=roominfo ./deploy.sh      # systemd service user
SESSION_SRC=/tmp/uestc_session.json ./deploy.sh
```

### 上传示例

```bash
scp -r server-plan-a user@server:/opt/roominfo
scp deploy_bundle/.uestc_session.json user@server:/tmp/uestc_session.json
ssh user@server 'cd /opt/roominfo && chmod +x deploy.sh && SESSION_SRC=/tmp/uestc_session.json ./deploy.sh'
```

### 运维

```bash
sudo systemctl status roominfo
sudo journalctl -u roominfo -f
sudo systemctl restart roominfo
```

无 systemd / 无 root 时：

```bash
tail -f run/roominfo.log
kill "$(cat run/roominfo.pid)"
```

### 仍需手工（设计如此）

- 本机桌面完成 MFA / `refresh_credentials`
- scp 包 + session
- 在 `.env` 填真实 `Authorization_code` 以启用邮件告警（缺失仅警告，不阻断部署）

## 会话过期

服务器不要跑 MFA。回本机：

1. `refresh_credentials.ps1`
2. 退出码 2 → 先 `bootstrap_browser.ps1`
3. 同步 `.uestc_session.json` 到服务器 `data/` 后执行 `./deploy.sh`

### 退出码

| 码 | 含义 |
|----|------|
| 0 | 成功（安装 + 按模式启动或 none） |
| 1 | 硬失败（缺 python、坏包、无凭据、systemd 强制但无权限等） |
| 2 | 安装完成但探测失败（默认不启动；`FORCE_START=1` 时仍启动并返回 2） |
"""
    _write(out_dir / "README.md", readme)

    (out_dir / "data").mkdir(exist_ok=True)
    _write(out_dir / "data" / ".gitkeep", "")

    copied_session = False
    if with_session:
        session = ROOT / ".uestc_session.json"
        if session.exists():
            _copy(session, out_dir / "data" / ".uestc_session.json")
            copied_session = True

    return {
        "path": str(out_dir),
        "with_session": copied_session,
        "files": sorted(
            str(p.relative_to(out_dir)).replace("\\", "/")
            for p in out_dir.rglob("*")
            if p.is_file()
        ),
    }


def build_local_package(out_dir: Path, with_state: bool) -> dict:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for name in LOCAL_FILES:
        src = ROOT / name
        if src.exists():
            _copy(src, out_dir / name)

    _write(
        out_dir / "requirements.txt",
        "\n".join(
            [
                "requests==2.31.0",
                "beautifulsoup4==4.12.2",
                "python-dotenv==1.0.0",
                "pyexecjs==1.5.1",
                "playwright>=1.50,<2",
                "",
            ]
        ),
    )

    _write(
        out_dir / ".env.example",
        "\n".join(
            [
                'API_USERNAME="Your Username"',
                'API_PASSWORD="Your Password"',
                'Authorization_code="Your SmtpPassword"',
                "",
                'ONLINE_SESSION_FILE=".uestc_session.json"',
                'ONLINE_BROWSER_STATE_FILE=".uestc_browser_state.json"',
                'ONLINE_BROWSER_PROFILE_DIR=".uestc_chrome_profile"',
                'ONLINE_BROWSER_EXECUTABLE=""',
                'ONLINE_BROWSER_REFRESH="true"',
                'ONLINE_BROWSER_TIMEOUT="90"',
                'ONLINE_REMEMBER_ME="true"',
                "",
            ]
        ),
    )

    readme = f"""# 本机工具包（方案 A 凭据维护）

生成时间: {datetime.now(timezone.utc).isoformat()}

## 用途

在有桌面/可弹浏览器的电脑上：

1. 首次建立可信浏览器态
2. 之后全自动刷新 session
3. 导出给服务器的 Cookie 文件

## 安装

需要**官方 CPython**（Windows 上 MSYS2 Python 通常装不上 Playwright）。

```powershell
py -3.13 -m pip install -r requirements.txt
```

复制 `.env.example` 为 `.env` 并填写账号。

## 日常命令

```powershell
.\\bootstrap_browser.ps1 --timeout 300
.\\refresh_credentials.ps1 --export-dir .\\deploy_bundle
```

把 `deploy_bundle\\.uestc_session.json` 同步到服务器后一条命令部署：

```bash
cd /opt/roominfo && chmod +x deploy.sh && \\
  SESSION_SRC=/path/to/.uestc_session.json ./deploy.sh
```

## 退出码

- `0` 成功
- `2` 需要 MFA：运行 `bootstrap_browser.ps1`
- 其他 失败
"""
    _write(out_dir / "README.md", readme)

    if with_state:
        for name in (
            ".uestc_session.json",
            ".uestc_browser_state.json",
            ".uestc_browser_state.json.meta.json",
        ):
            src = ROOT / name
            if src.exists():
                _copy(src, out_dir / name)

    return {
        "path": str(out_dir),
        "with_state": with_state,
        "files": sorted(
            str(p.relative_to(out_dir)).replace("\\", "/")
            for p in out_dir.rglob("*")
            if p.is_file()
        ),
    }


def write_root_readme(release_dir: Path) -> None:
    _write(
        release_dir / "README.md",
        f"""# Release packages

生成时间: {datetime.now(timezone.utc).isoformat()}

```text
release/
  server-plan-a/   # 上传到无 GUI 服务器
  local-tools/     # 留在本机刷凭据
```

## 快速流程

### 1) 本机

```powershell
cd local-tools
.\\bootstrap_browser.ps1 --timeout 300   # 仅首次/MFA
.\\refresh_credentials.ps1 --export-dir .\\deploy_bundle
```

### 2) 服务器

```bash
cd /opt/roominfo
# optional: SESSION_SRC=/tmp/uestc_session.json START_MODE=auto
./deploy.sh
```

`./deploy.sh` 全自动：OS 依赖（有权限时）/ venv / Plan A `.env` / session 发现 / 探测 / systemd 或 nohup 启动。

覆盖示例：

```bash
SESSION_SRC=/tmp/uestc_session.json ./deploy.sh
START_MODE=none ./deploy.sh          # 只安装不启动
START_MODE=nohup ./deploy.sh
FORCE_START=1 ./deploy.sh            # 探测失败仍启动
```

手工回退（`START_MODE=none` 之后）：

```bash
.venv/bin/python main.py
# 或
START_MODE=nohup ./deploy.sh
```

重新打包：

```powershell
python package_release.py --with-session --zip
```
""",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="打包方案 A 服务端与本机工具")
    parser.add_argument(
        "--out",
        default=str(RELEASE),
        help="输出目录，默认 ./release",
    )
    parser.add_argument(
        "--with-session",
        action="store_true",
        help="把当前 .uestc_session.json 打进服务端 data/（方便自己上传，勿外传）",
    )
    parser.add_argument(
        "--with-local-state",
        action="store_true",
        help="把当前 browser state/session 打进本机工具包",
    )
    parser.add_argument(
        "--zip",
        action="store_true",
        help="额外生成 zip 压缩包",
    )
    args = parser.parse_args()

    out_root = Path(args.out)
    if not out_root.is_absolute():
        out_root = ROOT / out_root
    out_root.mkdir(parents=True, exist_ok=True)

    server_info = build_server_package(
        out_root / "server-plan-a", with_session=args.with_session
    )
    local_info = build_local_package(
        out_root / "local-tools", with_state=args.with_local_state
    )
    write_root_readme(out_root)

    zips = []
    if args.zip:
        for name in ("server-plan-a", "local-tools"):
            folder = out_root / name
            zip_path = out_root / f"{name}.zip"
            if zip_path.exists():
                zip_path.unlink()
            shutil.make_archive(str(zip_path.with_suffix("")), "zip", root_dir=folder)
            zips.append(str(zip_path))

    result = {
        "success": True,
        "release_dir": str(out_root),
        "server": server_info,
        "local": local_info,
        "zips": zips,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
